repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/PyCQA/flake8/
    rev: 7.1.1
    hooks:
    - id: flake8
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3.9.13